### ISSUE TITLE
Page d'infos pratiques pour préparer son échange

### ISSUE THREAD

**Issue by Lgt2x** [TCastus/mobilite2-front#10]
Une page de bons conseils pour préparer son échange. On pense entre autres à y mettre : 
- Documents à fournir 
- Le logement 
- Le coût de la vie 
- Sécurité du pays 
- Les cours : correspondance entre cours INSA et cours dans l'université en question
- Des contacts pour chaque université 
- Comment marche l'affectation
- Lien vers MoveOn

**Comment by Dayfive5** [comment]
Est ce qu'on peut considérer que c'est un mix entre la page Mobilités avec les FAQ etc de chaque département et la page de détail de l'université ? Dans ce cas la je ferme l'issue
