### ISSUE TITLE
Design de la page d'accueil

### ISSUE THREAD

**Issue by Lgt2x** [TCastus/mobilite2-front#5]
Sur Canva, proposer une interface pour la page d'accueil avant l'implémentation

**Comment by alice76g** [comment]
Lien canva design des pages : https://www.canva.com/design/DAEXn_EqWJs/share/preview?token=ISHnCP625zUsJK7dJl4Vbw&role=EDITOR&utm_campaign=designshare&utm_source=sharebutton

**Comment by Lgt2x** [comment]
Le design qui a été proposé

![Page d'accueil du site](https://user-images.githubusercontent.com/44813937/112845629-5aa99980-90a5-11eb-9876-991530498a21.png)

**Comment by Lgt2x** [comment]
ça ressemble plus trop au canva, mais on a une page d'accueil plutôt cool avec la PR #30
